version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parkingdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


volumes:
  mysql-data:
